[versions]
agp = "8.13.0-alpha03"
kotlin = "2.0.21"


[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }

